### ISSUE TITLE
Pre/Post-Build Logs

### ISSUE THREAD

**Issue by ShaneMcC** [lunarianltd/makeimg.com#15]
Some actions happen pre/post build (checking out code, pushing finished image) that do not get logged as part of the build. These probably should so that if there is errors (eg missing permissions, or a bad submodule) that these will be visible to the user.

**Comment by csmith** [comment]
The logs now contain:

* Errors when cloning git repositories
* Errors when the daemon accepts the build job (e.g. invalid Dockerfiles)
* The usual build logs
* Errors when the daemon accepts the push job
* Output from the push

Which should cover every situation other than "makeimg is broken and should retry the build later".

The output isn't fantastic, especially the push part (I think it's writing a blank line every time it gets a progress update), but the web UI can make that a lot more acceptable at some point.
