### ISSUE TITLE
Build Dependencies (Local)

### ISSUE THREAD

**Issue by ShaneMcC** [lunarianltd/makeimg.com#4]
Given a repo "Y" that depends on "X" (eg as a base-image) it should be possible to trigger "Y" to rebuild if "X" is built.

Probably needs some kind of loop-avoidance to prevent build loops if someone does something dumb.

Also would be nice if this was a bit more intelligent than just "the remote repo was built" - eg if "Y" uses "from X:0.5" then a build on X:latest or X:0.6 shouldn't trigger "Y"

**Comment by csmith** [comment]
This has been implemented.

When makeimg successfully pushes an image, it will trigger any rule on makeimg whose most recent successful build pushed that image and tag.
