### ISSUE TITLE
Ability to view Build Output

### ISSUE THREAD

**Issue by ShaneMcC** [lunarianltd/makeimg.com#7]
I'd like to be able to see logs from my builds to see if anything is going wrong.

Ideally this would be "live" but post-build is also fine.

**Comment by csmith** [comment]
This is now recorded and exposed via the API.

It's pushed live-ish (buffering for a few hundred milliseconds), and the API supports getting log lines added after a specific ID and also provides a field to indicate if the build has finished. The web UI should be able to live update, when such a thing exists.
